#!/bin/sh

if [ "$1"x = "config"x ]; then
	echo "graph_title logpipe per-pipe statistics
graph_args --base 1000
graph_vlabel events / \${graph_period}
graph_category logpipe"

	first=1
	for file in /tmp/*.stat; do
		label=$(basename $file .sock.stat)
		label_repl=$(echo $label | sed s/\\./_/g)

		echo "${label_repl}.label $label"
		echo "${label_repl}.type DERIVE"
		echo "${label_repl}.max 1000000"
		echo "${label_repl}.min 0"
		if [ $first -eq 1 ]; then
			echo "${label_repl}.draw LINE"
			first=0
		else
			echo "${label_repl}.draw STACK"
		fi
	done
	exit
fi

for file in /tmp/*.stat; do
	label=$(basename $file .sock.stat)
	label_repl=$(echo $label | sed s/\\./_/g)

	value=$(egrep "^total" $file|cut -d' ' -f2)

	echo "${label_repl}.value $value"
done
